- name: Deploy Secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Create Mongo Secret
      community.kubernetes.k8s:
        kubeconfig: "/var/jenkins_home/.kube/config-jenkins"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mern-secrets
            namespace: mern-namespace
          type: Opaque
          data:
            mongo-root-password: "cGFzc3dvcmQxMjM=" # password123 in base64