- name: Deploy Secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Create Mongo Secret
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mern-secrets
            namespace: mern-namespace
          type: Opaque
          data:
            # Base64 for 'password123'
            mongo-root-password: "cGFzc3dvcmQxMjM="