- name: Deploy Secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Create MERN Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mern-secrets
            namespace: mern-namespace
          type: Opaque
          data:
            # password123 (Base64)
            mongo-root-password: "cGFzc3dvcmQxMjM="
            # mysecretkeyformongo123 (Base64)
            mongo-keyfile: "bXlzZWNyZXRrZXlmb3Jtb25nbzEyMw=="
            # supersecret (Base64)
            jwt-secret: "c3VwZXJzZWNyZXQ="
