- name: Deploy Secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Create Mongo Secret
      kubernetes.core.k8s:  # Updated to modern collection name
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mern-secrets
            namespace: mern-namespace
          type: Opaque
          data:
            mongo-root-password: "cGFzc3dvcmQxMjM="