- name: Deploy Secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Create Mongo Secret
      community.kubernetes.k8s:
        # REMOVED kubeconfig line here - it will use K8S_AUTH_KUBECONFIG env var
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: mern-secrets
            namespace: mern-namespace
          type: Opaque
          data:
            mongo-root-password: "cGFzc3dvcmQxMjM="