replicaCount: 3
backend:
  image: abhi144k/mern-backend
  tag: "latest"
  port: 5000
frontend:
  image: abhi144k/mern-frontend
  tag: "latest"
  port: 80
mongodb:
  image: mongo:5.0
  replicas: 3
  rootUser: admin
  rootPassword: password123
  keyFileContent: "bXlzZWNyZXRrZXlmb3Jtb25nbzEyMw=="